### ISSUE TITLE
Proxy authorization issue with Rally plugin

### ISSUE THREAD

**Issue by sagaut** [xebialabs-community/xlr-rally-plugin#10]
Hello!

I'm getting below error which accessing the Rally plugin - xlr-rally-plugin-3.3.0 with XL Release v8.0.1.

Can't connect to Rally: Server.
pyral.context.RallyRESTAPIError: 'Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authorization Required

The path variable http_proxy has been set to http://SVC_XLReleaseDEV:*********@proxy.lon.uk.organisation.com:80

The interesting part is that the issue disappears if proxy is authenticated by any of the following means:
1. Either click on on "Test connection" for ServiceNow under Settings -> Shared Configuration -> ServiceNow and then do a "Test connection" for Rally. This ensures that the proxy is authorized and Rally plugin is able to connect (provided the session is still valid, which usually is for at least 10 - 15 minutes).

2. Or access https://rally1.rallydev.com from Internet Explorer browser on the target server

Any pointers would help.

**Comment by vanstoner** [comment]
Can you share how you are specifying the proxy information in the Rally plugin and also in the ServiceNow plugin (ensuring of course you hide details).  Is there a domain element to this?

**Comment by sagaut** [comment]
Please find below the configuration settings.

![servicenowconfiguration](https://user-images.githubusercontent.com/40419656/41775605-2ad62ffa-7642-11e8-9560-183276616d56.JPG)

![rallyconfiguration](https://user-images.githubusercontent.com/40419656/41775611-31734e88-7642-11e8-9d1b-806c9d92e683.JPG)

**Comment by jdewinne** [comment]
I think the problem might be the proxy username and the `/` or `\`. Could you try escaping it or us the `username@domainname` notation?

**Comment by vanstoner** [comment]
Hi, 

Yes, working on that angle now.  In the past for a different plugin I had to make a fix to HttpRequest to handle domain notification.  It is worth trying the @ notation for this one @sagaut for this plugin, more to rule it out.  I will work on a work-around in the coming days.

**Comment by sagaut** [comment]
@vanstoner I have tried using multiple combinations such as uk\eagdev, uk/eagdev, uk@eagdev & eagdev@uk but **none** of them worked.

Kindly provide further inputs.

**Comment by vanstoner** [comment]
Hi @sagaut - can you try specifying your domain user as follows please?

<domain>%5C<domainuser>

Rob

**Comment by vanstoner** [comment]
I have updated the code with a change to the ordering of the proxy setting.  I have tested this using squid proxy with basic username/password authentication and the customer tested with domain authentication.  The actual issue was that no proxy for username/password code block was in reach.

Please verify and as appropriate close the issue @sagaut
