### ISSUE TITLE
Jar dependencies: rally Rest toolkit jar and gson-1.6.jar

### ISSUE THREAD

**Issue by vlussenburg** [xebialabs-community/xlr-rally-plugin#2]
This plugin could include Rally Rest toolkit and Gson as dependency in the XLDP.

Also probably we don't need the dependency on gson-1.6 anymore

**Comment by jdewinne** [comment]
I don't think this can be packaged as part of the plugin, as XLR doesn't has the XLDP concept.

**Comment by jdewinne** [comment]
Removing the gson dependency (v2.2.4) isn't possible. This is because the plugin uses the Rally java sdk, which depends on gson.
