### ISSUE TITLE
Plugin does not use proxy host

### ISSUE THREAD

**Issue by vlussenburg** [xebialabs-community/xlr-rally-plugin#3]
See quick hack in https://github.com/vlussenburg/xlr-rally-plugin/blob/master/src/main/resources/rally/CreateDefect.py

We need to put the proxy config into the create_client part.

**Comment by jdewinne** [comment]
Thanks for the link. See [v2.0.0](https://github.com/xebialabs-community/xlr-rally-plugin/releases/tag/v2.0.0)
